config/routes.rb
Rails.application.routes.draw do
  root :to => "rides#index"
  get 'users/show'
  get 'users/index'
  devise_for :users
  resources :users, only: [:index, :show]
  resources :rides
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile
  enum status: ["남성", "여성"]

  has_many :rides, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :sex])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /rides or /rides.json
  def index
    @allRides = Ride.all
    @rides = @allRides.where(end: false)
    if params[:departure].present?
      @rides = @rides.where(departure: params[:departure])
    end
  
    if params[:arrival].present?
      @rides = @rides.where(arrival: params[:arrival])
    end
  
    if params[:start_date].present?
      selected_date = Date.parse(params[:start_date])
      @rides = @rides.where(:reservation=> selected_date.beginning_of_day..selected_date.end_of_day)
    end
  
    if params[:samesex].present?
      @rides = @rides.where(samesex: params[:samesex])
    end
  end

  # GET /rides/1 or /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides or /rides.json
  def create
    @ride = Ride.new(ride_params)
    @ride.user = current_user
    @ride.end = false
    @ride.left = @ride.min-1
    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: "Ride was successfully created." }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1 or /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: "Ride was successfully updated." }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1 or /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: "Ride was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ride_params
      params.require(:ride).permit(:departure, :arrival, :reservation, :min, :memo, :via, :samesex, :left)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="kr">
  <head>
    <meta name="viewport" content="width=360px, height=640px">
    <title>Bluepoint</title>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/earlyaccess/notosanskr.css" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/shared/header" %>
    <%= yield %>
    <%= any_login_here if defined?(AnyLogin) %>
    <script src="https://kit.fontawesome.com/762239f8d9.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/rides/_form.html.erb
<%= form_with(model: ride, html: {:id => "resadd-form"}) do |form| %>
<div class="resadd">
    <div class="resadd__res"><span>예약 만들기</span></div>
    <div class="resadd__conf">
        <a href="/rides">
            <div class="resadd__conf__no">
                <i class="fas fa-times"></i>
                <span>취소</span>
            </div>
        </a>
        <div class="resadd__conf__yes">
            <i class="fas fa-check"></i>
            <%= form.submit "게시" %>
        </div>
    </div>
</div>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
        <% ride.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="resadd-form__departure">
    <span>출발지</span>
    <%= form.text_field :departure %>
    <i class="fas fa-search"></i>
  </div>

  <div class="resadd-form__arrival">
    <span>도착지</span>
    <%= form.text_field :arrival %>
    <i class="fas fa-search"></i>
  </div>

  <div class="resadd-form__time">
    <span>예약 시간</span>
    <%= form.datetime_field :reservation %>
  </div>

  <div class="resadd-form__maxx">
    <span>최소 인원 </span>
    <%= form.number_field :min %>
  </div>

  <div class="resadd-form__memo">
    <%= form.label :추가_메모 %>
    <%= form.text_field :memo %>
  </div>

  <div class="resadd-form__midinter">
    <span>중간 경유 여부</span>
    <%= form.check_box :via %>
  </div>

  <div class="resadd-form__sexseper">
    <span>동일 성별 승차 여부</span>
    <%= form.check_box :samesex %>
  </div>  
<% end %>
<%= stylesheet_link_tag 'newride', media: 'all', 'data-turbolinks-track' => true %>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form', ride: @ride %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<div class="reloc">
    <strong><span>용봉동</span></strong>
    <%= form_with url: "/rides", method: :get, local: true do |f| %>
    <div class = "search">
      <div>
        <%= f.label :출발지 %>
        <%= f.text_field :departure %>
      </div>
      <div>
        <%= f.label :도착지 %>
        <%= f.text_field :arrival %>
      </div>
      <div>
        <%= f.label :출발일 %>
        <%= f.date_field :start_date %>
        <%= f.submit :"검색"%>
      </div>
    </div>
    <% end %>
</div>
<% @rides.each do |ride| %>
<a href="rides/<%= ride.id %>">
  <div class="resinfo">
    <div class="resinfo__map">
      <img src="https://github.com/2021-oasis-hackathon/Bluepoint/blob/main/FE/exampleimage/mapexample.PNG?raw=true">
    </div>
    <div class="resinfo__detone">
      <span><%= ride.departure %> -> <%= ride.arrival %></span> <br>
      <%if ride.reservation != nil%>
      <span><%= ride.reservation.strftime("%m-%d %H:%M") %></span> <br>
      <%end%>
      <span><%= ride.memo %></span>
    </div>
    <div class="resinfo__dettwo">
      <span>출발 잔여 <%= ride.left %>석</span>   <br>
      <span class="money">예상 13000원</span>   <br>
      <% if ride.via %>
      <span class="via">동행 경유 가능</span> 
      <% end %>
      <% if ride.samesex %>
        <% if ride.user.sex==0 %>
      <span class="samesex">남성만 신청</span> 
        <% else %>
      <span class="samesex">여성만 신청</span> 
        <% end %>
      <% end %>
     </div>
  </div>
</a>
<% end %>


<br>
<div class="add__btn">
  <i class="fas fa-plus fa-2x">
  </i>
  <%= link_to '새글', new_ride_path %>
</div>


<nav class="nav">
  <ul type="none" class="nav__list">
    <li class="nav__btn">
      <a class="nav__link" href="#">
        <i class="fas fa-house-user fa-2x">
        </i>
      </a>
    </li>
    <li class="nav__btn">
      <a class="nav__link" href="chatlist.html">
        <i class="far fa-comment fa-2x"></i>
      </a>
    </li>
    <li class="nav__btn">
      <a class="nav__link" href="/users/<%= current_user.id %>">
        <i class="far fa-user fa-2x"></i>
      </a>
    </li>
  </ul>
</nav>
<%= stylesheet_link_tag 'ride', media: 'all', 'data-turbolinks-track' => true %>

app/views/rides/new.html.erb
<%= render 'form', ride: @ride %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @ride.user.name %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @ride.departure %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @ride.arrival %>
</p>

<p>
  <strong>Reservation:</strong>
  <%= @ride.reservation %>
</p>

<p>
  <strong>Min:</strong>
  <%= @ride.min %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @ride.memo %>
</p>

<p>
  <strong>Via:</strong>
  <%= @ride.via %>
</p>

<p>
  <strong>Samesex:</strong>
  <%= @ride.samesex %>
</p>

<p>
  <strong>Left:</strong>
  <%= @ride.left %>
</p>

<p>
  <strong>End:</strong>
  <%= @ride.end %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>


 <div class="map__info">
        <a href="/rides"><i class="fas fa-arrow-left fa-2x"></i></a>
        <img src="exampleimage/mapexample.png">
        <div class="map__info-top">
            <% if @ride.via %>
            <strong><span>중간 경유 가능</span></strong>
            <% end %>
            <% if !@ride.samesex %>
            <strong><span>성별 무관</span></strong>
            <% end %>
        </div>
    </div>
    <div class="deparrtemre">
        <div class="deparrtemre__dear">
            <span><%= @ride.departure %></span>
            <span> → </span>
            <span><%= @ride.arrival %></span>
        </div>
        <div class="deparrtemre__arr">
            <div class="deparrtemre__time">
                <span> <%= @ride.reservation %> </span>
            </div>
            <div class="deparrtemre__remain">
                <span>3석</span>
            </div>
        </div>
        
    </div>
    <div class="user__manner">
        <div class="user__manner-div">
            <div class="user__manner__profile"><img src="exampleimage/userduck.jpg"></div>
            <div class="user__manner_name"><span>duck</span></div>
        </div>
        <div class="user__manner_temper">
            <span>매너온도 </span>
            <span> 60℃</span>
            <i class="fas fa-thermometer-three-quarters"></i>
        </div>
    </div>
    <div class="detail__inscript">
        <p>
            <%= @ride.memo%>
        </p>
    </div>
    <div class="money__apply">
        <div class="money__apply__cost">
            <span>예상 금액 </span>
            <span>13000원</span>
        </div>
        <div class="money__apply__reap">
            <a href="home.html">
                <span>잔여 1석</span>
                <span>신청하기</span>
            </a>
        </div>
    </div>

app/views/shared/_header.html.erb
<div class="status-bar">
    <div class="status-bar__column">
        <span>No Service</span>
        <i class="fas fa-wifi"></i>
    </div>
    <div class="status-bar__column">
        <span>18:43</span>
    </div>
    <div class="status-bar__column">
        <span>73%</span>
        <i class="fas fa-battery-full fa-lg"></i>
        <i class="fas fa-bolt"></i>
    </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="main">
	<div class="profile__span">
		<strong> <span>  나의 프로필</span> </strong>
	</div>
	<div class="profile__info">
		<% if current_user.profile.attached? %>
        <img src="<%= url_for(current_user.profile) %>" alt="" class="profile_img rounded-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      	<% else %>
        <img src="https://picsum.photos/200" alt="" class="profile_img rounded-circle dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      	<% end %>
		<div class="profile__info-text">
		    <div class="profile__info-text__name">
                <span><%= @user.name %></span>
            </div>
			<div class="profile__info-text__adnum">
				<span>북구</span>
				<span>#<%= @user.id %></span>
			</div>
        </div>
	</div>
	<a href="/users/edit">
		<div class="profile__revise">
        	<span>프로필 수정</span>
		</div>
	</a>
	<a href="carpoolCollect.html">
		<div class="profile__carpoollist">
			<span>동승 내역</span>
		</div>
	</a>
		
	<div class="profile__temperture">
		<img src="https://github.com/2021-oasis-hackathon/Bluepoint/blob/main/FE/exampleimage/thermometer.jpg?raw=true"> 
		<div class="profile__temperture-context">
			<div class="profile__temperture-context__my"><span>현재 나의 온도</span></div>
			<div class="profile__temperture-context__tem"><span>78.6도</span></div>
			<div class="profile__temperture-context__per"><span>상위 3%</span></div>
		</div>
	</div>
</div>
<a href="/users/sign_out" data-method="delete">
	<div class="profile__logout">
		<span>로그아웃</span>
	</div>
</a>
<nav class="nav">
    <ul type="none" class="nav__list">
        <li class="nav__btn">
            <a class="nav__link" href="/rides">
                <i class="fas fa-home fa-2x"></i>
            </a>
        </li>
        <li class="nav__btn">
            <a class="nav__link" href="chatlist.html">
                <i class="far fa-comment fa-2x"></i>
            </a>
        </li>
        <li class="nav__btn">
            <a class="nav__link" href="#">
                <i class="fas fa-user fa-2x"></i>
            </a>
        </li>
    </ul>
</nav>
<%= stylesheet_link_tag 'profile', media: 'all', 'data-turbolinks-track' => true %>